services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7
    ports:
      - 6379:6379

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
